# steps:
# - name: 'docker'
#   args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']
# images:
# - 'gcr.io/$PROJECT_ID/gcpdevops'

steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t asia-south2-docker.pkg.dev/$PROJECT_ID/artifact-repo/python-image:tag1 .
  automapSubstitutions: true
images:
- 'asia-south2-docker.pkg.dev/$PROJECT_ID/artifact-repo/python-image:tag1'